### PR TITLE
Add new method `onBeforeGetContent`

### PR DESCRIPTION
**Pull request by MatthewHerbst**
This method allows the user to change the contents of the page before it is retrieved for printing. This occurs before the existing `onBeforePrint` which is called after the page content has been retrieved and right before the print window is opened.

Long term, it likely makes sense to change `onBeforePrint` to have this functionality, and then remove this function, since there is little use for it with this function existing.

### CODE REVIEW

**Review by MatthewHerbst — COMMENTED** [review]
Excited to see this in action @andfs

**Comment by andfs** [comment]
> Excited to see this in action @andfs

Thanks, man \o/

**Comment by mckelveygreg** [comment]
Thank you all for you work :) I've bee watching this for the last week 🚀

**Comment by MatthewHerbst** [comment]
Will get this released once I get #161 merged since right now a Promise rejection could result in the library still printing depending on if the user handled the error or not.

**Comment by MatthewHerbst** [comment]
Published as v2.4.0!

**Comment by andfs** [comment]
> Published as v2.4.0!

Great news \o/
Thanks :)

**Pull request merged**
