### PR TITLE
Fix issue #64: Print dialogue only open once in safari on Mac

### PR DESCRIPTION
**Pull request by eleonora-guidi**
Alternative solution to PR #56

### CODE REVIEW

**Review by MatthewHerbst — CHANGES_REQUESTED** [review]
Thanks for the PR! I'll test it out this weekend. One thing: can you please remove the CHANGELOG and version changes? Those will be in their own PR

**Comment by eleonora-guidi** [comment]
> Thanks for the PR! I'll test it out this weekend. One thing: can you please remove the CHANGELOG and version changes? Those will be in their own PR

Hi! Thank you, if you have time to test it in the weekend it would be really great! 
I have reverted the changes on the changelog and package.jsoon as requested. Hope it's fine.

**Review by MatthewHerbst — APPROVED** [review]
I've tested this on desktop Chrome and Safari and I've had others test it on mobile Safari on both iPad and iPhone, and it seems to work.

Apologies for the delay - I don't have an iOS device myself so it took a while to get it tested on mobile Safari.

Going to merge and publish, hopefully it solves issues for everyone!

**Comment by MatthewHerbst** [comment]
v2.1.3 is published! Please let me know if you run into an other issues

**Pull request merged**
