### PR TITLE
Allow passing of custom fonts

### LINKED ISSUE #281: Custom fonts not copying correctly
While Printing a component.
Most of the texts in original page vanishes in chrome somehow. but doing the same thing in safari or firefox doesn't produce such behaviour

behaviour in chrome
As you can see the labels texts in the original page at the back is is spomehow vanished
Screenshot 2020-08-29 at 11 32 30 PM

but in the firefox its behaviour is correct
Screenshot 2020-08-29 at 11 34 03 PM

P.S.- we are using custom font in the website

### PR DESCRIPTION
**Pull request by MatthewHerbst**
Fixes #281

### CODE REVIEW

**Comment by KiltedDrummer** [comment]
This looks like a good solution to the issue in #281 
Other than the conflict in the README that needs to be resolved.
Would love to see this get resolved, merged, and released since I am also hitting this issue

**Comment by MatthewHerbst** [comment]
Hi @KiltedDrummer have you been able to verify that this fixes the problem for you? I'm confident this doesn't break anything but I want to make sure it actually solves the problem 😄

**Comment by KiltedDrummer** [comment]
@MatthewHerbst Confirmed it on local.
I pulled down this branch, linked it, added font data, and no issues with printing.

**Review by KiltedDrummer — APPROVED** [review]

**Comment by MatthewHerbst** [comment]
Published as v`2.11.0` 🎉

**Pull request merged**
