### PR TITLE
Fixed import bug

### PR DESCRIPTION
**Pull request by aviklai**
Fix for #115.

### CODE REVIEW

**Comment by MatthewHerbst** [comment]
Thanks for the PR! Can you explain why this fixes it please? Changes make sense, just not sure what the issue with the current setup is

**Comment by aviklai** [comment]
@MatthewHerbst Hi, unfortunately I am not sure either why the previous setup didn't work but it looked like an issue with the entry point. I stumbled upon the issue after having the exact same error on my project.

I checked this new setup on a project I am working on and it looks o.k.
You can try to download from my fork and check that it works.

**Comment by hendra-go** [comment]
I can confirmed that this PR works.
But i think like @MatthewHerbst said, this is an export issue, not import issue, isn't it?

And i think is because UMD (Universal Module Definition) is well... more  "universal" and compatible with both AMD and CommonJS

**Comment by MatthewHerbst** [comment]
> And i think is because UMD (Universal Module Definition) is well... more "universal" and compatible with both AMD and CommonJS

Was the previous build (before 2.1) UMD? @sergeyshmakov did the TS PR change the build type?

**Comment by MatthewHerbst** [comment]
@gregnb do you have any knowledge here? I'm thinking we merge this unless anyone thinks it will cause other problems. @cmckni3 do you see any issues with the existing TS config, or with this PR?

**Comment by cmckni3** [comment]
Ah yes. The TS conversion added `libraryTarget: "commonjs"` to the webpack. UMD should be published to npm so it can be consumed in multiple environments (commonjs, AMD, ESM, etc).

**Comment by MatthewHerbst** [comment]
@gregnb can you please publish this fix as `2.1.1`? thanks!

Thanks @cmckni3!

**Comment by gregnb** [comment]
Soon as I land from vacation Saturday. Sorry for the delay

**Comment by gregnb** [comment]
@MatthewHerbst I'm still swamped from traveling. I've added you to have publishing access on npm. Can you test let me know if you have any issues?

**Comment by MatthewHerbst** [comment]
v2.1.1 is published. Please report any problems. Thank you everyone for the help fixing this!

(Thanks for the privileges @gregnb!)

**Comment by gregnb** [comment]
Awesome! No problem thanks for all your help :)

**Pull request merged**
