### PR TITLE
Support full load images before print

### PR DESCRIPTION
**Pull request by nhan-huynhvan**
Support full load images before print

### CODE REVIEW

**Comment by nhan-huynhvan** [comment]
@MatthewHerbst I closed and reopened new PR to squash the commits into a single commit

**Review by MatthewHerbst — APPROVED** [review]
Awesome, thanks! Going to test it locally and then merge it :)

**Comment by MatthewHerbst** [comment]
Released in v2.5.1, thank you!

**Comment by MatthewHerbst** [comment]
#200 #202 #203

**Pull request merged**
